### ISSUE TITLE
Running Pullio getting error "Error response from daemon: Get "https://cr.hotio.dev/v2/": dial tcp: lookup cr.hotio.dev on 192.168.0.1:53: no such host"

### ISSUE THREAD

**Issue by ryaneford** [hotio/pullio#14]
### Log

`Running with "DEBUG=" and "TAG=".
Current version: 0.0.6
Latest version: 0.0.6
FlareSolverr: Checking...
cloudflare-tunnels: Checking...
dashy: Checking...
ddns-updater: Checking...
docker-socket-proxy: Checking...
dozzle: Checking...
dozzle: Pulling image...
time="2024-02-11T00:00:06-05:00" level=warning msg="The \"PLEX_CLAIM\" variable is not set. Defaulting to a blank string."
time="2024-02-11T00:00:06-05:00" level=warning msg="The \"PLEX_ADVERTISE_IP\" variable is not set. Defaulting to a blank string."
time="2024-02-11T00:00:06-05:00" level=warning msg="The \"PLEX_PASS\" variable is not set. Defaulting to a blank string."
dozzle Pulling 
dozzle Pulled 
homepage: Checking...
plex: Checking...
plex: Pulling image...
time="2024-02-11T00:00:08-05:00" level=warning msg="The \"PLEX_CLAIM\" variable is not set. Defaulting to a blank string."
time="2024-02-11T00:00:08-05:00" level=warning msg="The \"PLEX_ADVERTISE_IP\" variable is not set. Defaulting to a blank string."
time="2024-02-11T00:00:08-05:00" level=warning msg="The \"PLEX_PASS\" variable is not set. Defaulting to a blank string."
plex Pulling 
plex Error 
Error response from daemon: Get "https://cr.hotio.dev/v2/": dial tcp: lookup cr.hotio.dev on 192.168.0.1:53: no such host
plex: Pulling failed!
portainer: Checking...
prowlarr: Checking...
prowlarr: Pulling image...
time="2024-02-11T00:00:10-05:00" level=warning msg="The \"PLEX_CLAIM\" variable is not set. Defaulting to a blank string."
time="2024-02-11T00:00:10-05:00" level=warning msg="The \"PLEX_ADVERTISE_IP\" variable is not set. Defaulting to a blank string."
time="2024-02-11T00:00:10-05:00" level=warning msg="The \"PLEX_PASS\" variable is not set. Defaulting to a blank string."
prowlarr Pulling 
prowlarr Error 
Error response from daemon: Get "https://cr.hotio.dev/v2/": dial tcp: lookup cr.hotio.dev on 192.168.0.1:53: no such host
prowlarr: Pulling failed!
qbitmanage: Checking...
qbitmanage: Pulling image...
time="2024-02-11T00:00:11-05:00" level=warning msg="The \"PLEX_CLAIM\" variable is not set. Defaulting to a blank string."
time="2024-02-11T00:00:11-05:00" level=warning msg="The \"PLEX_ADVERTISE_IP\" variable is not set. Defaulting to a blank string."
time="2024-02-11T00:00:11-05:00" level=warning msg="The \"PLEX_PASS\" variable is not set. Defaulting to a blank string."
qbit_manage Pulling 
qbit_manage Pulled 
qbittorrent: Checking...
qbittorrent: Pulling image...
time="2024-02-11T00:00:12-05:00" level=warning msg="The \"PLEX_CLAIM\" variable is not set. Defaulting to a blank string."
time="2024-02-11T00:00:12-05:00" level=warning msg="The \"PLEX_ADVERTISE_IP\" variable is not set. Defaulting to a blank string."
time="2024-02-11T00:00:12-05:00" level=warning msg="The \"PLEX_PASS\" variable is not set. Defaulting to a blank string."
qbittorrent Pulling 
qbittorrent Error 
Error response from daemon: Get "https://cr.hotio.dev/v2/": dial tcp: lookup cr.hotio.dev on 192.168.0.1:53: no such host
qbittorrent: Pulling failed!
radarr: Checking...
radarr: Pulling image...
time="2024-02-11T00:00:13-05:00" level=warning msg="The \"PLEX_CLAIM\" variable is not set. Defaulting to a blank string."
time="2024-02-11T00:00:13-05:00" level=warning msg="The \"PLEX_ADVERTISE_IP\" variable is not set. Defaulting to a blank string."
time="2024-02-11T00:00:13-05:00" level=warning msg="The \"PLEX_PASS\" variable is not set. Defaulting to a blank string."
radarr Pulling 
radarr Error 
Error response from daemon: Get "https://cr.hotio.dev/v2/": dial tcp: lookup cr.hotio.dev on 192.168.0.1:53: no such host
radarr: Pulling failed!
readarr: Checking...
readarr: Pulling image...
time="2024-02-11T00:00:14-05:00" level=warning msg="The \"PLEX_CLAIM\" variable is not set. Defaulting to a blank string."
time="2024-02-11T00:00:14-05:00" level=warning msg="The \"PLEX_ADVERTISE_IP\" variable is not set. Defaulting to a blank string."
time="2024-02-11T00:00:14-05:00" level=warning msg="The \"PLEX_PASS\" variable is not set. Defaulting to a blank string."
readarr Pulling 
readarr Pulled 
recyclarr: Checking...
sonarr: Checking...
sonarr: Pulling image...
time="2024-02-11T00:00:16-05:00" level=warning msg="The \"PLEX_CLAIM\" variable is not set. Defaulting to a blank string."
time="2024-02-11T00:00:16-05:00" level=warning msg="The \"PLEX_ADVERTISE_IP\" variable is not set. Defaulting to a blank string."
time="2024-02-11T00:00:16-05:00" level=warning msg="The \"PLEX_PASS\" variable is not set. Defaulting to a blank string."
sonarr Pulling 
sonarr Error 
Error response from daemon: Get "https://cr.hotio.dev/v2/": dial tcp: lookup cr.hotio.dev on 192.168.0.1:53: no such host
sonarr: Pulling failed!
tautulli: Checking...
tautulli: Pulling image...
time="2024-02-11T00:00:17-05:00" level=warning msg="The \"PLEX_CLAIM\" variable is not set. Defaulting to a blank string."
time="2024-02-11T00:00:17-05:00" level=warning msg="The \"PLEX_ADVERTISE_IP\" variable is not set. Defaulting to a blank string."
time="2024-02-11T00:00:17-05:00" level=warning msg="The \"PLEX_PASS\" variable is not set. Defaulting to a blank string."
tautulli Pulling 
tautulli Error 
Error response from daemon: Get "https://cr.hotio.dev/v2/": dial tcp: lookup cr.hotio.dev on 192.168.0.1:53: no such host
tautulli: Pulling failed!
vaultwarden: Checking...
youtubedl-material: Checking...
Pruning docker images...
Total reclaimed space: 0B`

**Comment by NLZ** [comment]
Read the announcement at the top of the page:
https://hotio.dev/containers/plex/

**Comment by mrhotio** [comment]
Also, use discord for support, like it says on the readme and website
