### ISSUE TITLE
Possible to only notify of update, without downloading the image?

### ISSUE THREAD

**Issue by zilexa** [hotio/pullio#3]
with `pull` the images are downloaded. Is it possible to configure the script, when notifying only, to check for updates without pulling the images in? I haven't found a command actually in the docker compose doc that does that (check current version against available one without downloading the image).

**Comment by mrhotio** [comment]
Technically it's possible to do, but it would complicate the script and I would loose the ability to read the labels....so the most useful info would be lost. So I decided against doing it...and even with just notifying and manually updating, you'd have to pull eventually...

**Comment by zilexa** [comment]
Yes your script is very clean. However perhaps the solution Watchtower implemented is relatively easy to use without limitations?
https://github.com/containrrr/watchtower/pull/674

I am no expert.. I prefer your neat solution instead of Watchtower but I prefer a solution that doesn't pull my 10GB of images daily.

**Comment by mrhotio** [comment]
if you use decent images, it isn't pulling in 10GB daily, only changes are pulled and my images use seperate layers for dependencies and app install. So worst case you'll pull in a few MB for the app.

**Comment by zilexa** [comment]
I didn't know that, thanks!
