### ISSUE TITLE
Script never updates anything

### ISSUE THREAD

**Issue by docwho76** [hotio/pullio#6]
Just prunes images and that’s it. I have it in root crontab like so

0 4 * * */usr/local/bin/pullio

And this is what I get when it runs

Running with "DEBUG=" and "TAG=".
jackett: Checking...
nzbhydra2: Checking...
ombi: Checking...
overseerr: Checking...
radarr: Checking...
resilio-sync: Checking...
sonarr: Checking...
tautulli: Checking...
traefik: Checking...
znc: Checking...
Pruning docker images...
Total reclaimed space: 0B

Running it in debug mode does nothing different. What am I doing wrong here? I’ve added all the tags to my docker-compose.yml and example 

  nzbhydra2:
    image: linuxserver/nzbhydra2:latest
    container_name: nzbhydra2
    restart: unless-stopped
    expose:
      - "5076"
    labels:
      - "traefik.http.routers.nzbhydra.rule=Host(`testing.test.org`)"
      - "traefik.http.routers.nzbhydra.entrypoints=websecure"
      - "traefik.http.routers.nzbhydra.tls.certresolver=route53"
      - "traefik.http.routers.nzbhydra.middlewares=authtraefik"
      - "traefik.http.routers.nzbhydra.middlewares=sslheader"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.generic.webhook=https://maker.ifttt.com/trigger/Pullio/with/key/fake-api-key"
      - "org.hotio.pullio.author.avatar=https://s.gravatar.com/avatar/99420eb3d52581434d66b08cf67f2e85"
    environment:
      - PUID=65534
      - PGID=65534
      - TZ=America/Los_Angeles
    volumes:
      - "/opt/docker-data/nzbhydra:/config"
      - "/mnt/freenas/downloads:/downloads"

so what am I doing wrong?

**Comment by mrhotio** [comment]
Did you update the images so that they actually have the labels applied? Just writing the labels in your compose isn't enough. Please use the discord for support questions in the future.
