### ISSUE TITLE
Can you add a link to the repo?

### ISSUE THREAD

**Issue by chmac** [hotio/pullio#7]
I read the images in the readme, but only after a second pass did I realise there was a link there. I automatically search the repo about section in GitHub for links to the web site of a project. Could you add the web site there? I can't submit a PR as it's only editable by repo admins.

**Comment by chmac** [comment]
PS> Thanks a lot for this script, looks like exactly what I was looking for.

**Comment by mrhotio** [comment]
Is clicking the image really too much work?

**Comment by chmac** [comment]
Yeah sure, you don't want people to use your software so it makes sense, make it harder for people to find the link. Genius.

**Comment by chmac** [comment]
Of course, people who use screen readers, they also don't need the link. That would just be too helpful. Let them suffer. Good job.

**Comment by mrhotio** [comment]
added the link to the sidebar just in case fyi
