### ISSUE TITLE
Compose V2 support?

### ISSUE THREAD

**Issue by NLZ** [hotio/pullio#9]
With the new `docker compose` could we get a detection for it, so it won't spin up linuxserver/docker-compose on machines without `docker-compose`?

**Comment by Sim0nW0lf** [comment]
Replacing the first line with this would do the trick right?
(I didn't test it maybe you could?)

`COMPOSE_BINARY="${COMPOSE_BINARY:-$(which 'docker-compose' || which 'docker compose')}"`

**Comment by NLZ** [comment]
Nope, that doesn't work because `which 'docker compose'` is not valid, as it's a plugin inside docker that gives it an extra parameter, not a separate executable.
Not sure what is the best way to detect it as it could be installed in multiple locations: https://github.com/docker/compose#linux

So maybe test if `docker compose version` returns anything valid like `Docker Compose version v2.20.2`?
Otherwise I think it returns something like `docker: 'compose' is not a docker command.`

**Comment by nonCarcer** [comment]
Change first line to:
`COMPOSE_BINARY="${COMPOSE_BINARY:-$(which 'docker')}"`

Then change lines 33-49 to look like:

`compose_pull_wrapper() {
    if [[ -z ${COMPOSE_BINARY} ]]; then
        "${DOCKER_BINARY}" run --rm -v /var/run/docker.sock:/var/run/docker.sock -v "$1:$1" -w="$1" linuxserver/docker compose pull "$2"
    else
        cd "$1" || exit 1
        "${COMPOSE_BINARY}"  compose pull "$2"
    fi
}

compose_up_wrapper() {
    if [[ -z ${COMPOSE_BINARY} ]]; then
        "${DOCKER_BINARY}" run --rm -v /var/run/docker.sock:/var/run/docker.sock -v "$1:$1" -w="$1" linuxserver/docker compose up -d --always-recreate-deps "$2"
    else
        cd "$1" || exit 1
        "${COMPOSE_BINARY}"  compose up -d --always-recreate-deps "$2"
    fi
}`

as a plus, if you happen to have a QNAP nas and need to get around mapfile not being present comment line 140

`docker_output="$("${DOCKER_BINARY}" ps --format '{{.Names}}' | sort -k1 | awk '{ print $1 }')"

# Initialize an array to store container names
containers=()

# Use a while loop to read lines from the output and store them in the array
while IFS= read -r container_name; do
    containers+=("$container_name")
done <<< "$docker_output"`
